### ISSUE TITLE
Subscription stops and dosent restart

### ISSUE THREAD

**Issue by thoj** [chuank/node-red-contrib-particle#16]
Hi

Seems like something is stopping the subscription and the subscription does not start again before i redeploy the flow. 

![issue1](https://user-images.githubusercontent.com/153440/50956441-f302d600-14bb-11e9-957e-a50d2145ef7b.PNG)
Here I just redeployed the flow.
![issue2](https://user-images.githubusercontent.com/153440/50956442-f302d600-14bb-11e9-96f3-49f4319a6e0d.PNG)
Here is the flow. Nothing fancy.

Any suggestions on what to do?

**Comment by chuank** [comment]
Hi @thoj can you set console logging to `trace` in your Node-RED server (see `~/.node-red/settings.js`) and post the redacted logs of when your SSE loses the connection?

Particle just released [v1.0.0 firmware for Core/Photon/P1/Electron](https://community.particle.io/t/particle-firmware-updates-thread/14378/68) with breaking changes to pub/sub. Have your devices upgraded to v1.0.0 when you experience the dropouts?

The nodes have already followed the deprecation notices from the v0.8.0 firmware but this obviously needs a bit of monitoring.

**Comment by chuank** [comment]
I've been testing SSEs sent out via the Publish node and from a Photon running on v1.0.0 firmware. It's been going for two days so far but I'll keep monitoring it.

![image](https://user-images.githubusercontent.com/1781911/51080261-4f6c2c80-172c-11e9-843e-12d4e12e002f.png)

Maybe check your mqtt server, and the QoS and retain settings in your mqtt nodes?

**Comment by chuank** [comment]
also refer to particle-iot/particle-api-js#95

**Comment by jbesselm** [comment]
I am also seeing this behavior,  In my case this usually happens when there is brief internet disruption.  Before the updated nodes I could force a re-connect by sending a message to the input of the SSE node with the message.topic as devid and the message.payload as the device id. This no longer seems to work.
![image](https://user-images.githubusercontent.com/7621132/51151347-7adc3d80-1838-11e9-8f21-994b48c4805d.png)

**Comment by jbesselm** [comment]
I got my re-connect to work by making a change in line 231 of particle.js
The updated node file had
![image](https://user-images.githubusercontent.com/7621132/51155584-f2649980-1845-11e9-87d9-33836b7728c4.png)

I changed line 231 to look like the previous version if (val != null).

I don't know javascript, but this seemed to restore a re-connect with an incomming message to the SSE node.

**Comment by chuank** [comment]
@jbesselm checking for a non-null value will force a reconnect anytime an upstream message payload enters the node. Perhaps allowing just a `msg.topic` of `reconnect` to force reconnections will be a good way to filter out unintended upstream messages connected by mistake.

If you can, please post your redacted node-red logs here (set debug level to trace), particularly around the moment your SSE disconnects. I've added some traces to check if abrupt stream disconnections are handled by the event listeners to the Particle JS API.

**Comment by GrantsPi** [comment]
I too have the issue of the SSE not being kept alive after a day or so.  Looking forward to any suggestions on this issue.

**Comment by chuank** [comment]
@GrantsPi thanks for the report; the key issue is related to particle-iot/particle-api-js#95.

Until it gets resolved, I'll add a keepalive mechanism within the SSE node in the next patch release.

**Comment by chuank** [comment]
v1.1.0 is released, which should hopefully address this issue. Upgrading via node-red palette. Please help to test and report back here, thanks.

**Comment by GrantsPi** [comment]
chuank, just to let you know that after 24 hours the SSE is still connected/reporting; will keep you posted over the next day or two.  Thanks for the fix!

**Comment by chuank** [comment]
Thanks for getting back @GrantsPi, I will keep track on my end too. Cheers

**Comment by thoj** [comment]
Seems to work fine! Thank you! :)

**Comment by GrantsPi** [comment]
Still working well! Thank you.

**Comment by marc-gist** [comment]
I seem to be getting this issue :(
