### ISSUE TITLE
Multiple SSE listeners spawned over time

### ISSUE THREAD

**Issue by steves2j** [chuank/node-red-contrib-particle#18]
Creating an issue from subject discussed in PR [#17](https://github.com/chuank/node-red-contrib-particle/pull/17) so that we keep this issue seperate from the PR.

steve wrote:
> I'm currently trying to track down and issue with your SSE module where it's spawning new event listeners and am getting multiple messages where I should only be getting one. Might be the reconnect or redeploy is not destroying the old listeners.

chuank wrote:
> Perhaps the keepalive mechanism introduced to fix [#16](https://github.com/chuank/node-red-contrib-particle/issues/16) inadvertently spawned new connections, even though I thought I've done the proper GC'ing on existing connections.
> There is also this long-standing issue on [particle-iot/particle-api-js#95](https://github.com/particle-iot/particle-api-js/issues/95) that points to the Particle JS API implementation. Those were the things that were left on the to-do plate when I last worked on fixing the multiple connection woes of the SSE node. Previously, before I ported the node to use the Particle JS API (<1.0.0), this was not an issue.

Currently I've not been able to reproduce it on demand. It could be that the system works fine for several hours without spawing extra listeners, but other times it creates multiple listeners in a short period.
I've reduced the time for reconnect to every 10seconds, but this does not increase the spawn. I may have to try what is detailed in issue 95 and disconnect the network and see if that does it.

**Comment by steves2j** [comment]
I've found the issue and have added a fix to the pull request currently open.

Basically the re-init of the sse via the setInterval was the issue, where the interval was not being cleared when a new flow deployment was made.
So have updated the SSE function to store the setInterval handle and then add a clearInterval in the close event.

**Comment by chuank** [comment]
Thanks @steves2j much appreciated, merging your PR. I'll continue to test it on my flows for a bit before publishing an updated version on npm. Cheers
