### ISSUE TITLE
Particle Nodes make Node-Red crash on Linode Server

### ISSUE THREAD

**Issue by JoelEB** [chuank/node-red-contrib-particle#19]
Hi, First, thanks for all your work on this library. It's been a great addition to Node-Red. I've used it a lot on Raspberry Pi with no issues. I recently tried running a similar setup on my Linode server. However, every time I try to deploy a flow with the particle nodes, it crashes the whole node-red server. The Linode server is running Ubuntu 18.04 LTS and is only hosting a simple wordpress site. The flows deploy and run fine until a connect the particle nodes to my Particle account. Then when I deploy, the console prints out the following and exits: 

```
21 Jan 22:23:55 - [info] Starting flows
21 Jan 22:23:55 - [info] Started flows
21 Jan 22:23:55 - [info] Server now running at http://127.0.0.1:1880/
^[[A^[[B21 Jan 22:28:28 - [info] Stopping flows
21 Jan 22:28:28 - [info] Stopped flows
21 Jan 22:28:28 - [info] Starting flows
21 Jan 22:28:29 - [error] [particle-var:da913197.19c328] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:8c75483a.60ab48] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:de19e63e.e8ecb] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:77d3fba5.a64f64] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:792abe3c.a63a2] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:2d099ace.c41396] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:d5f27d8a.c44438] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:d0f91ed1.dbede] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-func:b907630f.078458] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-func:90d4178b.a43aa8] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:3d45918c.8b3c1e] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:80f347a4.bdb36] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:7d1a6d0a.1d1bc4] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:3247945b.83bb44] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:31eb95d7.cf12fa] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [error] [particle-var:34d796c1.00a5c2] TypeError: Cannot read property 'host' of null
21 Jan 22:28:29 - [info] Started flows
21 Jan 22:34:07 - [info] Stopping flows
21 Jan 22:34:07 - [info] Stopped flows
21 Jan 22:34:07 - [info] Starting flows
21 Jan 22:34:07 - [info] Started flows
21 Jan 22:34:08 - [red] Uncaught Exception:
21 Jan 22:34:08 - TypeError: that.param.trim is not a function
    at ParticleFunc.on (/home/joeleb/.node-red/node_modules/node-red-contrib-particle/particle/particle.js:850:19)
    at emitOne (events.js:116:13)
    at ParticleFunc.emit (events.js:211:7)
    at ParticleFunc.Node.emit (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:185:20)
    at Timeout.setTimeout [as _onTimeout] (/home/joeleb/.node-red/node_modules/node-red-contrib-particle/particle/particle.js:833:11)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) 
```

I'm not sure what I'm missing. Any help you can offer is much appreciated. Thanks for your time.

**Comment by chuank** [comment]
Thanks for the kind words.

That error implies that the hostname stored in the particle credentials
isn't valid for some reason. If it were null it should have reverted to the
default particle.io server. Try deleting your particle credentials and
setting it up again?

What are you sending into the particle-var node too?

**Comment by JoelEB** [comment]
I deleted the flow, reset my access token, and started from scratch with a smaller flow. I can pull variable information just fine from particle-var. But, when I start adding the particle-func nodes, that's when Node-Red crashes. 

Here's how my variables are configured:
<img width="512" alt="Screen Shot 2020-01-22 at 11 51 01 AM" src="https://user-images.githubusercontent.com/1051208/72927217-03769f00-3d13-11ea-9f02-724f3225135c.png">

And, here's my function configuration:

<img width="497" alt="Screen Shot 2020-01-22 at 12 05 02 PM" src="https://user-images.githubusercontent.com/1051208/72927255-14bfab80-3d13-11ea-8672-cfa4d8590ea0.png">

To trigger the particle-var and -func nodes, I'm just using a timestamp that triggers every 5 seconds. I then have some graphs from the dashboard nodes that display live water data from my turtle tank. 

Is it possible that I am triggering in too quickly? Every time it crashes, it prints the same error that I posted above.

**Comment by JoelEB** [comment]
OK, I think this issue is bigger than the particle nodes because I'm still getting crashes with just the simple flow running. I'll have to dig deeper into Node-red. Thank you for your time!

**Comment by chuank** [comment]
5 second intervals are within the rate limits on the particle cloud.

It sounds like a credentials data corruption on the Pi.

On a sidenote it looks like you typed in `topic:param` in the parameter field.

In order to send parameters into a particleFunc node (in your case, calling setUpThres with I'd imagine a number as an argument), you have to construct a message with 'param' as the topic string, along with whatever payload you wish to send.

Using `topic:param` the way you did will just send the literal string 'topic:param' as the function argument for your setUpThres Particle function on your device.

If you mean to send changing parameter values based on upstream nodes, leave the parameter field empty (it will then show a grayed out topic:param, which was meant as a hint).

**Comment by JoelEB** [comment]
Thanks for the tip! That explains why setting my thresholds never quite worked the way I expected. 

I'm running the node-red server on a Linode server, similar to a Digital Ocean "Droplet", which is what I also host my websites from. I was reading somewhere that my server could be blocking websockets which is what the particle nodes use. If that was the case, it wouldn't work at all, correct? Whereas I'm seeing it work for a little bit, but as soon as I exit the command line, it seems to stop node-red. I've configured it to start on boot, and it should stay running after I terminate my ssh session. But, as soon as I do, I can no longer access the node-red gui or the dashboard. It's the damnedest thing. I've never seen anything like it while running node-red on a pi.

**Comment by chuank** [comment]
You could install `particle-cli` on your server to test your server's connection to the Particle cloud. `particle-cli` also leverages the Particle JS SDK so it's a good litmus test to narrow down the root of your crashes.

The Particle server uses COAP via port 443 (hence api.particle.io:443 as the default cloud server url). If your server's firewall is configured to allow SSL you should already be good to go. I'm not familiar with Linode so can't help further on that.

Finally, I'd monitor the free memory on your server, and also refer to the NR docs on how to start the service with a specific amount of RAM. Use `pm2` to help you manage NR crashes and auto-restarts.

The issues are not related to this node so this is as far as I'll comment based on my own experience with NR+Particle. Good luck!
