### ISSUE TITLE
Dependency should be updated

### ISSUE THREAD

**Issue by cbrandlehner** [chuank/node-red-contrib-particle#22]
When installing this plugin, npm warns about the following:

`WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3`

**Comment by chuank** [comment]
This is related to the `particle-api-js` dependency that is maintained by Particle. I've lodged this issue there:
https://github.com/particle-iot/particle-api-js/issues/163

Depending on their outcome, the next patch release may include dependency overrides to help address these deprecation warnings.
