### ISSUE TITLE
Trouble with SSE

### ISSUE THREAD

**Issue by GrantsPi** [chuank/node-red-contrib-particle#23]
Is anyone having trouble with the SSE node?

Everything has been working just fine until this aftenoon.  Now all my SSE nodes are reporting errors.  The function nodes and variable nodes are working fine.

The SSE node returns a string of "" along with the error - refer to debugging.

Nothing else had changed.  And the function and variable nodes work just fine.

Thanks

**Comment by chuank** [comment]
SSE seems to be working – v1.2.0 and tested on a Photon on 3.3.1 firmware. You might want to check if your login token has expired.
