### ISSUE TITLE
Duplicate SSE subscribe

### ISSUE THREAD

**Issue by skeller2015** [chuank/node-red-contrib-particle#3]
I have had some instances where multiple SSE subscribes on the same flow get started somehow.  The result is that the downstream flow runs multiple times for the same event.  What would cause duplicate subscriptions to get created?

**Comment by chuank** [comment]
apologies on the necro-reply, but this could be related to previous evenstreams not closing properly when the flow was re-deployed. v0.0.9 should resolve this.
